## Numpy 
넘파이는 고성능 수치계산을 위한 라이브러리이다.  
scikit-learn은 numpy 배열을 입력으로 받는다. ndarray는 다차원 배열이다. 

**Numpy 로 하는 일**
* List 자료로 Numpy array 로 만들기
* 행렬 형태 확인하기
* 행렬 형태 바꾸기
* 행렬 데이터 만들기
* 행렬의 일부 구간 추출하기
* 행렬끼리 더하기, 곱하기, 행렬 원소간의 연산
* 행렬끼리 합치기
* 그외 연산

In [1]:
import numpy as np  # Make numpy available using np.

# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
    print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
    print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [2]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [3]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int32'>


In [4]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.18429578 0.33283673 0.37785263]
 [0.85716804 0.85646945 0.08588187]
 [0.40592032 0.88913763 0.01953647]]


In [5]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


### 행렬의 형태

In [7]:
# 행렬의 형태 변경하기
c = [[1,2,3],[4,5,6]]

C = np.array(c)

print('Numpy array C: \n', C)
print('Shape of C :', C.shape)

C = C.reshape(3,2)
print('Numpy array C (reshaped to (3,2)): \n', C)   

Numpy array C: 
 [[1 2 3]
 [4 5 6]]
Shape of C : (2, 3)
Numpy array C (reshaped to (3,2)): 
 [[1 2]
 [3 4]
 [5 6]]


In [9]:
C_colvector = C.reshape(-1,1)   # 행의 크기는 미정이지만 열의 크기는 1로 고정하겠다는 표현입니다.
C_colvector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 행렬의 기본연산

In [12]:
E = np.arange(1,7).reshape(2,3);
print(E)
print(E + 1)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]


In [13]:
E + E

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
F = np.array([1,2]).reshape(-1,1) 
E * F   #  E 의 첫 행에는 1을 곱하고 두 번쨰 행에는 2를 곱한 결과을 얻습니다.

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [15]:
H = np.array([1,0,1]).reshape(-1,1)
print(E)
print(H)

[[1 2 3]
 [4 5 6]]
[[1]
 [0]
 [1]]


In [16]:
E.dot(H)  

array([[ 4],
       [10]])

In [17]:
np.hstack((E,E))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [18]:
np.vstack((E,E))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [19]:
S = np.array([3,1,2,4,6,5,8,7,9]).reshape(3,3)
S

array([[3, 1, 2],
       [4, 6, 5],
       [8, 7, 9]])

In [20]:
S.sum()

45

In [23]:
S.sum(axis=1) #행렬의 열끼리의 합

array([ 6, 15, 24])

In [22]:
S.sum(axis=0) # 행렬의 행끼리의 합

array([15, 14, 16])