# Numpy Basic

In [0]:
import numpy as np

## data type

array의 dtype을 본다. 

In [0]:
arr = np.array([[1., 2, 3], [1, 2, 3]])

In [3]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [4]:
arr = arr.astype(np.int32)
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [5]:
arr = np.array([[1., 2, 3], [1, 2, 3]], dtype=np.uint8)
arr.dtype

dtype('uint8')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [6]:
len(arr.shape)

2

In [7]:
arr.shape

(2, 3)

size 확인

In [8]:
arr.size

6

dtype 확인

In [9]:
arr.dtype

dtype('uint8')

## Reshape

In [10]:
arr.shape

(2, 3)

Reshape 

In [11]:
arr = arr.reshape([1, 6])
arr.shape

(1, 6)

In [0]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [13]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [14]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [15]:
arr = arr.reshape(-1, 3)
arr.shape

(2, 3)

random array 생성

In [16]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [17]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [18]:
arr = arr.reshape(-1, 2, 1, 1, 1, 1)
arr.shape

(32, 2, 1, 1, 1, 1)

In [19]:
arr

array([[[[[[-0.86899787]]]],



        [[[[ 0.22499069]]]]],




       [[[[[-0.67124271]]]],



        [[[[-0.076994  ]]]]],




       [[[[[ 3.53595765]]]],



        [[[[-0.77949134]]]]],




       [[[[[ 0.8694452 ]]]],



        [[[[ 0.62652476]]]]],




       [[[[[-0.39494107]]]],



        [[[[ 0.31428832]]]]],




       [[[[[-0.07569447]]]],



        [[[[ 0.37009195]]]]],




       [[[[[ 1.05485635]]]],



        [[[[ 0.46799115]]]]],




       [[[[[ 0.95459608]]]],



        [[[[-0.23151284]]]]],




       [[[[[ 1.01735728]]]],



        [[[[-0.57991636]]]]],




       [[[[[-0.6090072 ]]]],



        [[[[-0.37614782]]]]],




       [[[[[-0.132049  ]]]],



        [[[[-0.21248771]]]]],




       [[[[[-0.89327687]]]],



        [[[[-0.5908971 ]]]]],




       [[[[[ 0.30787374]]]],



        [[[[ 0.18303432]]]]],




       [[[[[-1.46628967]]]],



        [[[[-0.18379787]]]]],




       [[[[[ 1.09026331]]]],



        [[[[ 1.35737595]]]]],




       [[[

## Ravel

In [20]:
arr.shape

(32, 2, 1, 1, 1, 1)

In [21]:
arr = arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [22]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [23]:
arr.shape

(64,)

In [24]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

In [0]:
arr = arr.ravel()

In [26]:
arr.shape

(64,)

In [0]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)

In [28]:
arr.shape

(1, 64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [29]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
zeros = np.zeros(1)
zeros

array([0.])

In [31]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [33]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [34]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [35]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [0]:
nums = [1, 2, 3, 4, 5]

In [38]:
nums[2:]

[3, 4, 5]

In [39]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [40]:
nums[4]

[1, 2, 3]

In [41]:
arr[1][2]

5

In [42]:
arr[1, 2]

5

# Slicing

In [43]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [45]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

In [46]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Boolean Indexing

In [47]:
data = np.random.randn(3, 3)
data

array([[-1.97533421, -0.2358559 , -1.17406676],
       [-0.73292732, -0.16959406,  0.75976814],
       [-2.43656677, -0.99668254, -1.35174169]])

In [48]:
data <= 0

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [0]:
data[data <= 0] = 1

In [50]:
data

array([[1.        , 1.        , 1.        ],
       [1.        , 1.        , 0.75976814],
       [1.        , 1.        , 1.        ]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [0]:
import numpy as np

In [52]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [55]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [57]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [58]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [59]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [60]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [0]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size=9).reshape(3, 3)

In [64]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [65]:
arr + arr_2

array([[[2, 1, 0],
        [1, 2, 2],
        [1, 1, 1]],

       [[2, 2, 0],
        [1, 2, 2],
        [2, 2, 1]],

       [[2, 1, 1],
        [1, 2, 1],
        [2, 2, 0]]])

In [66]:
arr * arr_2

array([[[1, 0, 0],
        [0, 1, 1],
        [0, 0, 0]],

       [[1, 1, 0],
        [0, 1, 1],
        [1, 1, 0]],

       [[1, 0, 0],
        [0, 1, 0],
        [1, 1, 0]]])

In [67]:
np.sum(arr)

19

In [68]:
np.sum(arr + arr_2)

37

In [69]:
arr + arr_2

array([[[2, 1, 0],
        [1, 2, 2],
        [1, 1, 1]],

       [[2, 2, 0],
        [1, 2, 2],
        [2, 2, 1]],

       [[2, 1, 1],
        [1, 2, 1],
        [2, 2, 0]]])

In [70]:
np.max(arr + arr_2)

2

In [71]:
np.min(arr + arr_2)

0

In [72]:
np.max(arr + arr_2, -1)

array([[2, 2, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [73]:
arr + arr_2

array([[[2, 1, 0],
        [1, 2, 2],
        [1, 1, 1]],

       [[2, 2, 0],
        [1, 2, 2],
        [2, 2, 1]],

       [[2, 1, 1],
        [1, 2, 1],
        [2, 2, 0]]])

In [74]:
np.sum(arr + arr_2, axis=-1)

array([[3, 5, 3],
       [4, 5, 5],
       [4, 4, 4]])

In [75]:
np.mean(arr)

0.7037037037037037

In [76]:
arr = np.array([1, 6, 3, 7, 3, 2, 9, 0, 2])
arr

array([1, 6, 3, 7, 3, 2, 9, 0, 2])

In [77]:
np.argmax(arr)

6

In [78]:
np.argmin(arr)

7

In [0]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

In [80]:
np.unique(arr)

array([1, 3, 5, 6])

In [81]:
np.unique(arr, return_counts=True)

(array([1, 3, 5, 6]), array([1, 3, 1, 2]))